---
title: 100 Cities Variant
subtitle: Card gallery style with info below
date: last-modified
date-format: "DD-MMM-YYYY"
format:
  html:
    page-layout: full
    theme: none
    minimal: true
    toc: false
---

A recreation of the [100 cities bucket list](https://www.delicious.com.au/travel/international/gallery/100-cities-deserve-place-travel-bucket-list/o4lzlr69?page=12).

```{r}
#| code-fold: true

library(pixture)

dfr <- data.frame(
  paths = c(
    "https://img.delicious.com.au/DGZCHR1s/del/2018/12/paris-france-97370-2.jpg",
    "https://img.delicious.com.au/ttEaxwsa/del/2018/12/new-york-usa-97371-2.jpg",
    "https://img.delicious.com.au/BTJu9b76/del/2018/12/rome-italy-97372-2.jpg",
    "https://img.delicious.com.au/ZOmI5Coz/del/2018/12/london-uk-97375-2.jpg",
    "https://img.delicious.com.au/ErfAJ_zb/del/2018/12/tokyo-japan-97376-2.jpg",
    "https://img.delicious.com.au/-a6x6DpP/del/2018/12/lisbon-portugal-97377-2.jpg",
    "https://img.delicious.com.au/wvdCCshN/del/2018/12/barcelona-spain-97378-2.jpg",
    "https://img.delicious.com.au/x0_XXdmh/del/2018/12/honolulu-hawaii-97380-2.jpg",
    "https://img.delicious.com.au/WIXeICQZ/del/2018/12/istanbul-turkey-97382-2.jpg",
    "https://img.delicious.com.au/QvcF4Hu0/del/2018/12/bangkok-thailand-97383-2.jpg",
    "https://img.delicious.com.au/2AHRryRu/del/2018/12/agra-india-97385-2.jpg",
    "https://img.delicious.com.au/3M0FMB5C/del/2018/12/cairo-egypt-97390-2.jpg",
    "https://img.delicious.com.au/zYT2qxH4/del/2018/12/helsinki-finland-97391-2.jpg",
    "https://img.delicious.com.au/0UYOAZzI/del/2018/12/ubud-bali-indonesia-97392-2.jpg",
    "https://img.delicious.com.au/9Ow8JVHu/del/2018/12/berlin-germany-97393-2.jpg",
    "https://img.delicious.com.au/1ri8bDOT/del/2018/12/shanghai-china-97394-2.jpg",
    "https://img.delicious.com.au/r2iDWaS5/del/2018/12/las-vegas-usa-97395-2.jpg",
    "https://img.delicious.com.au/YQa2u6-g/del/2018/12/venice-italy-97397-1.jpg",
    "https://img.delicious.com.au/5hc3JSiw/del/2018/12/cape-town-south-africa-97398-2.jpg",
    "https://img.delicious.com.au/JkpxIMZo/del/2018/12/rio-de-janeiro-brazil-97399-2.jpg",
    "https://img.delicious.com.au/TxSUCqgo/del/2018/12/singapore-singapore-97400-2.jpg",
    "https://img.delicious.com.au/-5nxKI4B/del/2018/12/toronto-canada-97401-2.jpg",
    "https://img.delicious.com.au/AT4SCR_Q/del/2018/12/seoul-south-korea-97402-2.jpg",
    "https://img.delicious.com.au/XbEWSGhz/del/2018/12/casablanca-morocco-97403-2.jpg",
    "https://img.delicious.com.au/NO1JKQbi/del/2018/12/sydney-australia-97405-2.jpg",
    "https://img.delicious.com.au/CUQ1XYkN/del/2018/12/lima-peru-97406-2.jpg",
    "https://img.delicious.com.au/C7eDVGxM/del/2018/12/beijing-china-97407-2.jpg",
    "https://img.delicious.com.au/-wdYryVH/del/2018/12/buenos-aires-argentina-97408-2.jpg",
    "https://img.delicious.com.au/NSk5SvLt/del/2018/12/edinburgh-scotland-97409-2.jpg",
    "https://img.delicious.com.au/y8WbXmoN/del/2018/12/los-angeles-97410-2.jpg",
    "https://img.delicious.com.au/IfD4cIOg/del/2018/12/copenhagen-denmark-97411-2.jpg",
    "https://img.delicious.com.au/Odi3Q_q0/del/2018/12/osaka-japan-97412-2.jpg",
    "https://img.delicious.com.au/h5ocbm6d/del/2018/12/auckland-new-zealand-97413-2.jpg",
    "https://img.delicious.com.au/tJbFHPBs/del/2018/12/mumbai-india-97414-2.jpg",
    "https://img.delicious.com.au/JRqPDi6I/del/2018/12/dubai-united-arab-emirates-97416-2.jpg",
    "https://img.delicious.com.au/Pq5tF1id/del/2019/01/munich-germany-99993-3.jpg",
    "https://img.delicious.com.au/RKkLKri4/del/2018/12/hong-kong-china-97417-2.jpg",
    "https://img.delicious.com.au/mCVCUFM-/del/2018/12/qatar-state-of-qatar-97418-2.jpg",
    "https://img.delicious.com.au/dUsJaCMv/del/2018/12/seattle-usa-97420-2.jpg",
    "https://img.delicious.com.au/HXG-5zOx/del/2018/12/oslo-norway-97421-2.jpg",
    "https://img.delicious.com.au/IAvISo4V/del/2018/12/bath-uk-97422-2.jpg",
    "https://img.delicious.com.au/po-s_ja5/del/2018/11/athens-greece-92871-3.jpg",
    "https://img.delicious.com.au/S-8TVY1G/del/2018/12/vienna-austria-97425-2.jpg",
    "https://img.delicious.com.au/NxQ49oAL/del/2018/12/madrid-spain-97426-2.jpg",
    "https://img.delicious.com.au/MmaZLcyU/del/2018/12/dublin-republic-of-ireland-97428-2.jpg",
    "https://img.delicious.com.au/E6jO20Oq/del/2018/12/florence-italy-97429-2.jpg",
    "https://img.delicious.com.au/w0ZIWSz6/del/2018/12/bruges-belgium-97430-2.jpg",
    "https://img.delicious.com.au/sRlG9Yqa/del/2018/12/krakow-poland-97431-2.jpg",
    "https://img.delicious.com.au/qNXdJPqd/del/2018/12/amsterdam-holland-97432-2.jpg",
    "https://img.delicious.com.au/z6Nwu6s8/del/2018/12/stockholm-sweden-97433-2.jpg",
    "https://img.delicious.com.au/m-MMHY82/del/2018/12/ljubljana-slovenia-97434-2.jpg",
    "https://img.delicious.com.au/DTPuY7Rs/del/2018/12/hanoi-vietnam-97435-2.jpg",
    "https://img.delicious.com.au/GK2D3BLF/del/2018/12/wellington-new-zealand-97436-2.jpg",
    "https://img.delicious.com.au/uAvgs844/del/2018/12/nice-france-97437-1.jpg",
    "https://img.delicious.com.au/daj4fCrs/del/2018/12/vancouver-canada-97438-2.jpg",
    "https://img.delicious.com.au/Yj7W5YCj/del/2018/12/hallstatt-austria-97440-2.jpg",
    "https://img.delicious.com.au/V4liCscH/del/2018/12/havana-cuba-97441-2.jpg",
    "https://img.delicious.com.au/0DXtNjmz/del/2018/12/mexico-city-97442-2.jpg",
    "https://img.delicious.com.au/mJCBvmTM/del/2018/12/beirut-lebanon-97443-2.jpg",
    "https://img.delicious.com.au/Bt28G1xt/del/2018/12/salzburg-austria-97444-2.jpg",
    "https://img.delicious.com.au/W97vX457/del/2018/12/sao-paolo-brazil-97445-2.jpg",
    "https://img.delicious.com.au/U5BPim7t/del/2018/12/prague-czech-republic-97446-2.jpg",
    "https://img.delicious.com.au/SEjXnLuV/del/2018/12/kyoto-japan-97447-2.jpg",
    "https://img.delicious.com.au/T7tDeVQV/del/2018/12/marrakech-morocco-97448-2.jpg",
    "https://img.delicious.com.au/CH_y9R1g/del/2018/12/st-petersburg-russia-97449-2.jpg",
    "https://img.delicious.com.au/As-0XdKV/del/2018/12/san-francisco-usa-97450-2.jpg",
    "https://img.delicious.com.au/GLKZ7On_/del/2018/12/oxford-uk-97451-2.jpg",
    "https://img.delicious.com.au/vKiFEkMz/del/2018/12/melbourne-australia-97452-2.jpg",
    "https://img.delicious.com.au/TITRTFAX/del/2018/12/kingston-jamaica-97453-2.jpg",
    "https://img.delicious.com.au/LdTRytKk/del/2018/12/amman-jordan-97454-2.jpg",
    "https://img.delicious.com.au/1E9ATrG7/del/2018/12/lagos-nigeria-97455-2.jpg",
    "https://img.delicious.com.au/_zFbpPkH/del/2018/12/new-orleans-usa-97456-2.jpg",
    "https://img.delicious.com.au/R4eUMyBK/del/2018/12/san-jose-costa-rica-97459-2.jpg",
    "https://img.delicious.com.au/Ajsm0aLu/del/2018/12/tallinn-estonia-97460-2.jpg",
    "https://img.delicious.com.au/dWLrFTPz/del/2018/12/suva-fiji-97461-2.jpg",
    "https://img.delicious.com.au/xcS3H8vq/del/2018/12/jarkarta-indonesia-97462-2.jpg",
    "https://img.delicious.com.au/89Tkufuf/del/2018/12/new-delhi-india-97463-2.jpg",
    "https://img.delicious.com.au/hd0g2cR-/del/2018/12/adelaide-australia-97464-2.jpg",
    "https://img.delicious.com.au/gHB4aSRR/del/2018/12/male-maldives-97466-2.jpg",
    "https://img.delicious.com.au/9jTXbVWY/del/2018/12/luxembourg-luxembourg-97467-2.jpg",
    "https://img.delicious.com.au/Ddy8qHBR/del/2018/12/kuala-lumpur-malaysia-97469-2.jpg",
    "https://img.delicious.com.au/DuTFgzOE/del/2018/12/glasgow-scotland-97470-2.jpg",
    "https://img.delicious.com.au/PtDJbPk-/del/2018/12/valletta-malta-97471-2.jpg",
    "https://img.delicious.com.au/9e1uckIy/del/2018/12/kathmandu-nepal-97472-2.jpg",
    "https://img.delicious.com.au/X73tQW8J/del/2018/12/brussels-belgium-97473-2.jpg",
    "https://img.delicious.com.au/Vy6xTaOh/del/2018/12/panama-city-panama-97474-2.jpg",
    "https://img.delicious.com.au/BQA_95U5/del/2018/12/bucharest-romania-97475-2.jpg",
    "https://img.delicious.com.au/JxSrdYNH/del/2018/12/cardiff-wales-97477-2.jpg",
    "https://img.delicious.com.au/mih19QSM/del/2018/12/manila-philippines-97478-2.jpg",
    "https://img.delicious.com.au/p_CQKccC/del/2018/12/castries-saint-lucia-97479-2.jpg",
    "https://img.delicious.com.au/Xtx2tJOh/del/2018/12/apia-samoa-97482-2.jpg",
    "https://img.delicious.com.au/TWo_E-PN/del/2018/12/bern-switzerland-97483-2.jpg",
    "https://img.delicious.com.au/wS8lfHBO/del/2018/12/taipei-taiwan-97484-2.jpg",
    "https://img.delicious.com.au/NFvp2n1a/del/2018/12/budapest-hungary-97486-2.jpg",
    "https://img.delicious.com.au/5zsxMNLQ/del/2018/12/reykjavik-iceland-97487-2.jpg",
    "https://img.delicious.com.au/IT7sw9ZI/del/2020/09/milan-italy-138760-2.jpg",
    "https://img.delicious.com.au/vQHPqjhj/del/2018/11/nashville-usa-96643-3.jpg",
    "https://img.delicious.com.au/wk4hf0TM/del/2019/07/perth-australia-111196-3.jpg",
    "https://img.delicious.com.au/TcVOVMrp/del/2018/12/hobart-australia-97485-2.jpg",
    "https://img.delicious.com.au/3jQWB_TO/del/2018/12/tripoli-libya-97465-2.jpg"
  ),
  city = c(
    "Paris",
    "New York",
    "Rome",
    "London",
    "Tokyo",
    "Lisbon",
    "Barcelona",
    "Honolulu",
    "Istanbul",
    "Bangkok",
    "Agra",
    "Cairo",
    "Helsinki",
    "Bali",
    "Berlin",
    "Shanghai",
    "Las Vegas",
    "Venice",
    "Cape Town",
    "Rio de Janeiro",
    "Singapore",
    "Toronto",
    "Seoul",
    "Casablanca",
    "Sydney",
    "Lima",
    "Beijing",
    "Buenos Aires",
    "Edinburgh",
    "Los Angeles",
    "Copenhagen",
    "Osaka",
    "Auckland",
    "Mumbai",
    "Dubai",
    "Munich",
    "Hong Kong",
    "Doha",
    "Seattle",
    "Oslo",
    "Bath",
    "Athens",
    "Vienna",
    "Madrid",
    "Dublin",
    "Florence",
    "Bruges",
    "Krakow",
    "Amsterdam",
    "Stockholm",
    "Ljubljana",
    "Hanoi",
    "Wellington",
    "Nice",
    "Vancouver",
    "Hallstatt",
    "Havana",
    "Mexico city",
    "Beirut",
    "Salzburg",
    "Sao Paolo",
    "Prague",
    "Kyoto",
    "Marrakech",
    "St Petersburg",
    "San Francisco",
    "Oxford",
    "Melbourne",
    "Kingston",
    "Amman",
    "Lagos",
    "New Orleans",
    "San Jose",
    "Tallin",
    "Suva",
    "Jakarta",
    "New Delhi",
    "Adelaide",
    "Male",
    "Luxembourg",
    "Kuala Lumpur",
    "Glasgow",
    "Valletta",
    "Kathmandu",
    "Brussels",
    "Panama city",
    "Bucharest",
    "Cardiff",
    "Manila",
    "Castries",
    "Apia",
    "Bern",
    "Taipei",
    "Budapest",
    "Reykjavik",
    "Milan",
    "Nashville",
    "Perth",
    "Hobart",
    "Tripoli"
  ),
  country = c(
    "France",
    "United States",
    "Italy",
    "United Kingdom",
    "Japan",
    "Portugal",
    "Spain",
    "United States",
    "Turkiye",
    "Thailand",
    "India",
    "Egypt",
    "Finland",
    "Indonesia",
    "Germany",
    "China",
    "United States",
    "Italy",
    "South Africa",
    "Brazil",
    "Singapore",
    "Canada",
    "South Korea",
    "Morocco",
    "Australia",
    "Peru",
    "China",
    "Argentina",
    "Scotland",
    "United States",
    "Denmark",
    "Japan",
    "New Zealand",
    "India",
    "United Arab Emirates",
    "Germany",
    "China",
    "Qatar",
    "United States",
    "Norway",
    "United Kingdom",
    "Greece",
    "Austria",
    "Spain",
    "Ireland",
    "Italy",
    "Belgium",
    "Poland",
    "Netherlands",
    "Sweden",
    "Slovenia",
    "Vietnam",
    "New Zealand",
    "France",
    "Canada",
    "Austria",
    "Cuba",
    "Mexico",
    "Lebanon",
    "Austria",
    "Brazil",
    "Czechia",
    "Japan",
    "Morocco",
    "Russia",
    "United States",
    "United Kingdom",
    "Australia",
    "Jamaica",
    "Jordan",
    "Nigeria",
    "United States",
    "Costa Rica",
    "Estonia",
    "Fiji",
    "Indonesia",
    "India",
    "Australia",
    "Maldives",
    "Luxembourg",
    "Malaysia",
    "United Kingdom",
    "Malta",
    "Nepal",
    "Belgium",
    "Panama",
    "Romania",
    "United Kingdom",
    "Philippines",
    "St Lucia",
    "Samoa",
    "Switzerland",
    "Taiwan",
    "Hungary",
    "Iceland",
    "Italy",
    "United States",
    "Australia",
    "Australia",
    "Libya"
  ),
  tagline = c(
    "The City of Love and Lights",
    "The City That Never Sleeps",
    "The Eternal City",
    "Where History Meets Modernity",
    "The Heartbeat of Japan",
    "Where Culture Meets Coastline",
    "Gaudí’s Playground by the Sea",
    "Where Aloha Lives",
    "The Crossroads of Continents",
    "Gateway to Thailand’s Heart and Soul",
    "Home of the Majestic Taj Mahal",
    "The Land of Ancient Wonders",
    "Northern Beauty by the Sea",
    "The Island of the Gods",
    "History and Hip Vibes",
    "The Pearl of the Orient",
    "The Entertainment Capital of the World",
    "The Floating City of Romance",
    "Where Nature and Culture Converge",
    "The City of Sun, Samba, and Splendor",
    "The Lion City Roars",
    "Diversity in Every Corner",
    "Where Tradition Meets Tomorrow",
    "Morocco's Burgeoning Metropolis",
    "Harbour City Splendor",
    "A Culinary Capital of the World",
    "Where Ancient Meets Innovational",
    "The Paris of South America",
    "Scotland’s Historic and Cultural Gem",
    "City of Angels and Stars",
    "Scandinavia’s Cool Capital",
    "The Nation's Kitchen",
    "City of Sails and Adventures",
    "The City of Dreams",
    "City of Superlatives",
    "Bavaria's Heartbeat",
    "Asia's World City",
    "The Jewel of the Middle East",
    "The Emerald City",
    "Viking Heritage and Modern Chic",
    "The Quintessential English Spa City",
    "The Cradle of Western Civilization",
    "A Symphony of Art and History",
    "Passion and Elegance",
    "The Heartbeat of Ireland",
    "Art in Every Corner",
    "The Venice of the North",
    "A Polish Treasure",
    "Canals and Creativity",
    "Where Innovation Meets Tradition",
    "The Green Capital of Europe",
    "Rich Heritage and Modern Vibe",
    "Windy Wellington's Wonders",
    "The Jewel of the French Riviera",
    "Where Nature and Urbanity Coalesce",
    "The Iconic Alpine Village",
    "Colonial Charm and Rhythmic Beats",
    "A City Steeped in History",
    "Lebanon's Resilient Heart",
    "Mozart's Melodious Abode",
    "Brazil's Bustling Metropolis",
    "Golden Spires and Timeless Beauty",
    "Where Tradition Blossoms",
    "The Red City of Morocco",
    "The Cultural Heart of Russia",
    "Innovation and Iconic Views",
    "A University City with Charm",
    "A Cultural Melting Pot Down Under",
    "Reggae Beats and Beach Retreats",
    "A City of Ancient Heritage",
    "Nigeria's Dynamic Metropolis",
    "A City's Jazz and Soul",
    "The Garden City",
    "A Fairytale Capital",
    "Island Charm with Fijian Smiles",
    "A Melting Pot of Cultures",
    "A Historic and Modern Capital",
    "Australia’s Festival City",
    "A Tropical Paradise",
    "A Gem in Europe's Heart",
    "A Fusion of Cultures",
    "Scotland’s Cultural Powerhouse",
    "A Cultural and Historical Jewel",
    "Gateway to the Himalayas",
    "The Heart of Europe",
    "A Hub of Culture and Commerce",
    "A City of Hidden Charms",
    "A City with a Heart and Soul",
    "A City Alive with Energy",
    "A Slice of Paradise",
    "The Heart of Samoa",
    "A Swiss Gem of Tranquility",
    "Asia's Hidden Gem",
    "The Pearl of the Danube",
    "The Land of Fire and Ice",
    "Italy's Fashion Capital",
    "The Music City",
    "A West Coast Wonderland",
    "A Tale of Two Towns",
    "A City with Layers of History"
  )
)
```

Generate captions.

```{r}
captions <- paste0(
  "<div style='line-height:0.1;'>",
  paste0("<div style='text-transform:uppercase;letter-spacing:3px;margin-bottom:0.2em;line-height:1.2;font-size:0.8em;color:#abb2b9;'><b>", dfr$country, "</b></div><br>"),
  paste0("<div style='font-size:1.6em;margin-bottom:0.2em;line-height:1;color:#34495e;'><b>", dfr$city, "</b></div><br>"),
  paste0("<div style='line-height:1.2;font-size:0.9em;color:#808b96;'>", dfr$tagline, "</div>"),
  "</div>"
)
```

It would be better to just add CSS classes above and set the styles in a separate CSS document. Refresh the page to see shuffle in action.

```{r}
pixgallery(
  dfr$paths, 
  captions, 
  caption_valign = "below", 
  h = "250px", 
  w = "200px",
  layout = "grid",
  shuffle = TRUE,
  link = FALSE
)
```
