---
title: Cities bucket list
subtitle: Card gallery with custom HTML
date: last-modified
date-format: "DD-MMM-YYYY"
format:
  html:
    page-layout: full
---

A recreation of the [100 cities bucket list](https://www.delicious.com.au/travel/international/gallery/100-cities-deserve-place-travel-bucket-list/o4lzlr69?page=12).

```{r}
#| code-fold: true

library(pixture)

dfr <- data.frame(
  paths = c(
    "https://img.delicious.com.au/DGZCHR1s/del/2018/12/paris-france-97370-2.jpg",
    "https://img.delicious.com.au/ttEaxwsa/del/2018/12/new-york-usa-97371-2.jpg",
    "https://img.delicious.com.au/BTJu9b76/del/2018/12/rome-italy-97372-2.jpg",
    "https://img.delicious.com.au/ZOmI5Coz/del/2018/12/london-uk-97375-2.jpg",
    "https://img.delicious.com.au/ErfAJ_zb/del/2018/12/tokyo-japan-97376-2.jpg",
    "https://img.delicious.com.au/-a6x6DpP/del/2018/12/lisbon-portugal-97377-2.jpg",
    "https://img.delicious.com.au/wvdCCshN/del/2018/12/barcelona-spain-97378-2.jpg",
    "https://img.delicious.com.au/x0_XXdmh/del/2018/12/honolulu-hawaii-97380-2.jpg",
    "https://img.delicious.com.au/WIXeICQZ/del/2018/12/istanbul-turkey-97382-2.jpg",
    "https://img.delicious.com.au/QvcF4Hu0/del/2018/12/bangkok-thailand-97383-2.jpg",
    "https://img.delicious.com.au/2AHRryRu/del/2018/12/agra-india-97385-2.jpg",
    "https://img.delicious.com.au/3M0FMB5C/del/2018/12/cairo-egypt-97390-2.jpg",
    "https://img.delicious.com.au/zYT2qxH4/del/2018/12/helsinki-finland-97391-2.jpg",
    "https://img.delicious.com.au/0UYOAZzI/del/2018/12/ubud-bali-indonesia-97392-2.jpg",
    "https://img.delicious.com.au/9Ow8JVHu/del/2018/12/berlin-germany-97393-2.jpg",
    "https://img.delicious.com.au/1ri8bDOT/del/2018/12/shanghai-china-97394-2.jpg",
    "https://img.delicious.com.au/r2iDWaS5/del/2018/12/las-vegas-usa-97395-2.jpg",
    "https://img.delicious.com.au/YQa2u6-g/del/2018/12/venice-italy-97397-1.jpg",
    "https://img.delicious.com.au/5hc3JSiw/del/2018/12/cape-town-south-africa-97398-2.jpg",
    "https://img.delicious.com.au/JkpxIMZo/del/2018/12/rio-de-janeiro-brazil-97399-2.jpg",
    "https://img.delicious.com.au/TxSUCqgo/del/2018/12/singapore-singapore-97400-2.jpg",
    "https://img.delicious.com.au/-5nxKI4B/del/2018/12/toronto-canada-97401-2.jpg",
    "https://img.delicious.com.au/AT4SCR_Q/del/2018/12/seoul-south-korea-97402-2.jpg",
    "https://img.delicious.com.au/XbEWSGhz/del/2018/12/casablanca-morocco-97403-2.jpg",
    "https://img.delicious.com.au/NO1JKQbi/del/2018/12/sydney-australia-97405-2.jpg",
    "https://img.delicious.com.au/CUQ1XYkN/del/2018/12/lima-peru-97406-2.jpg",
    "https://img.delicious.com.au/C7eDVGxM/del/2018/12/beijing-china-97407-2.jpg",
    "https://img.delicious.com.au/-wdYryVH/del/2018/12/buenos-aires-argentina-97408-2.jpg",
    "https://img.delicious.com.au/NSk5SvLt/del/2018/12/edinburgh-scotland-97409-2.jpg",
    "https://img.delicious.com.au/y8WbXmoN/del/2018/12/los-angeles-97410-2.jpg",
    "https://img.delicious.com.au/IfD4cIOg/del/2018/12/copenhagen-denmark-97411-2.jpg",
    "https://img.delicious.com.au/Odi3Q_q0/del/2018/12/osaka-japan-97412-2.jpg",
    "https://img.delicious.com.au/h5ocbm6d/del/2018/12/auckland-new-zealand-97413-2.jpg",
    "https://img.delicious.com.au/tJbFHPBs/del/2018/12/mumbai-india-97414-2.jpg",
    "https://img.delicious.com.au/JRqPDi6I/del/2018/12/dubai-united-arab-emirates-97416-2.jpg",
    "https://img.delicious.com.au/Pq5tF1id/del/2019/01/munich-germany-99993-3.jpg",
    "https://img.delicious.com.au/RKkLKri4/del/2018/12/hong-kong-china-97417-2.jpg",
    "https://img.delicious.com.au/mCVCUFM-/del/2018/12/qatar-state-of-qatar-97418-2.jpg",
    "https://img.delicious.com.au/dUsJaCMv/del/2018/12/seattle-usa-97420-2.jpg",
    "https://img.delicious.com.au/HXG-5zOx/del/2018/12/oslo-norway-97421-2.jpg",
    "https://img.delicious.com.au/IAvISo4V/del/2018/12/bath-uk-97422-2.jpg",
    "https://img.delicious.com.au/po-s_ja5/del/2018/11/athens-greece-92871-3.jpg",
    "https://img.delicious.com.au/S-8TVY1G/del/2018/12/vienna-austria-97425-2.jpg",
    "https://img.delicious.com.au/NxQ49oAL/del/2018/12/madrid-spain-97426-2.jpg",
    "https://img.delicious.com.au/MmaZLcyU/del/2018/12/dublin-republic-of-ireland-97428-2.jpg",
    "https://img.delicious.com.au/E6jO20Oq/del/2018/12/florence-italy-97429-2.jpg",
    "https://img.delicious.com.au/w0ZIWSz6/del/2018/12/bruges-belgium-97430-2.jpg",
    "https://img.delicious.com.au/sRlG9Yqa/del/2018/12/krakow-poland-97431-2.jpg",
    "https://img.delicious.com.au/qNXdJPqd/del/2018/12/amsterdam-holland-97432-2.jpg",
    "https://img.delicious.com.au/z6Nwu6s8/del/2018/12/stockholm-sweden-97433-2.jpg",
    "https://img.delicious.com.au/m-MMHY82/del/2018/12/ljubljana-slovenia-97434-2.jpg",
    "https://img.delicious.com.au/DTPuY7Rs/del/2018/12/hanoi-vietnam-97435-2.jpg",
    "https://img.delicious.com.au/GK2D3BLF/del/2018/12/wellington-new-zealand-97436-2.jpg",
    "https://img.delicious.com.au/uAvgs844/del/2018/12/nice-france-97437-1.jpg",
    "https://img.delicious.com.au/daj4fCrs/del/2018/12/vancouver-canada-97438-2.jpg",
    "https://img.delicious.com.au/Yj7W5YCj/del/2018/12/hallstatt-austria-97440-2.jpg",
    "https://img.delicious.com.au/V4liCscH/del/2018/12/havana-cuba-97441-2.jpg",
    "https://img.delicious.com.au/0DXtNjmz/del/2018/12/mexico-city-97442-2.jpg",
    "https://img.delicious.com.au/mJCBvmTM/del/2018/12/beirut-lebanon-97443-2.jpg",
    "https://img.delicious.com.au/Bt28G1xt/del/2018/12/salzburg-austria-97444-2.jpg",
    "https://img.delicious.com.au/W97vX457/del/2018/12/sao-paolo-brazil-97445-2.jpg"
  ),
  city = c(
    "Paris",
    "New York",
    "Rome",
    "London",
    "Tokyo",
    "Lisbon",
    "Barcelona",
    "Honolulu",
    "Istanbul",
    "Bangkok",
    "Agra",
    "Cairo",
    "Helsinki",
    "Bali",
    "Berlin",
    "Shanghai",
    "Las Vegas",
    "Venice",
    "Cape Town",
    "Rio de Janeiro",
    "Singapore",
    "Toronto",
    "Seoul",
    "Casablanca",
    "Sydney",
    "Lima",
    "Beijing",
    "Buenos Aires",
    "Edinburgh",
    "Los Angeles",
    "Copenhagen",
    "Osaka",
    "Auckland",
    "Mumbai",
    "Dubai",
    "Munich",
    "Hong Kong",
    "Doha",
    "Seattle",
    "Oslo",
    "Bath",
    "Athens",
    "Vienna",
    "Madrid",
    "Dublin",
    "Florence",
    "Bruges",
    "Krakow",
    "Amsterdam",
    "Stockholm",
    "Ljubljana",
    "Hanoi",
    "Wellington",
    "Nice",
    "Vancouver",
    "Hallstatt",
    "Havana",
    "Mexico city",
    "Beirut",
    "Salzburg",
    "Sao Paolo"
  ),
  country = c(
    "France",
    "United States",
    "Italy",
    "United Kingdom",
    "Japan",
    "Portugal",
    "Spain",
    "United States",
    "Turkiye",
    "Thailand",
    "India",
    "Egypt",
    "Finland",
    "Indonesia",
    "Germany",
    "China",
    "United States",
    "Italy",
    "South Africa",
    "Brazil",
    "Singapore",
    "Canada",
    "South Korea",
    "Morocco",
    "Australia",
    "Peru",
    "China",
    "Argentina",
    "Scotland",
    "United States",
    "Denmark",
    "Japan",
    "New Zealand",
    "India",
    "United Arab Emirates",
    "Germany",
    "China",
    "Qatar",
    "United States",
    "Norway",
    "United Kingdom",
    "Greece",
    "Austria",
    "Spain",
    "Ireland",
    "Italy",
    "Belgium",
    "Poland",
    "Netherlands",
    "Sweden",
    "Slovenia",
    "Vietnam",
    "New Zealand",
    "France",
    "Canada",
    "Austria",
    "Cuba",
    "Mexico",
    "Lebanon",
    "Austria",
    "Brazil"
  ),
  tagline = c(
    "The City of Love and Lights",
    "The City That Never Sleeps",
    "The Eternal City",
    "Where History Meets Modernity",
    "The Heartbeat of Japan",
    "Where the Sun Sets Over the Sea",
    "Gaudí’s Playground by the Sea",
    "Where Aloha Lives",
    "The Crossroads of Continents",
    "The City of Angels",
    "Home of the Majestic Taj Mahal",
    "The Land of Ancient Wonders",
    "Northern Beauty by the Sea",
    "The Island of the Gods",
    "History and Hip Vibes",
    "The Pearl of the Orient",
    "The Entertainment Capital of the World",
    "The Floating City of Romance",
    "Where Nature and Culture Converge",
    "The Marvelous City",
    "The Lion City Roars",
    "Diversity in Every Corner",
    "Where Tradition Meets Tomorrow",
    "Morocco's Burgeoning Metropolis",
    "Harbour City Splendor",
    "A Culinary Capital of the World",
    "Where Ancient Meets Innovational",
    "The Paris of South America",
    "Scotland’s Historic and Cultural Gem",
    "City of Angels and Stars",
    "Scandinavia’s Cool Capital",
    "City of Sails and Adventures",
    "The Nation's Kitchen",
    "The City of Dreams",
    "City of Superlatives",
    "Bavaria's Heartbeat",
    "Asia's World City",
    "The Jewel of the Middle East",
    "The Emerald City",
    "Viking Heritage and Modern Chic",
    "The Georgian Gem",
    "The Cradle of Western Civilization",
    "The Imperial City",
    "Passion and Elegance",
    "The Heartbeat of Ireland",
    "Art in Every Corner",
    "The Venice of the North",
    "A Polish Treasure",
    "Canals and Creativity",
    "Where Innovation Meets Tradition",
    "The Green Capital of Europe",
    "Rich Heritage and Modern Vibe",
    "Windy Wellington's Wonders",
    "The Jewel of the French Riviera",
    "Where Nature and Urbanity Coalesce",
    "The Iconic Alpine Village",
    "Colonial Charm and Rhythmic Beats",
    "A City Steeped in History",
    "Lebanon's Resilient Heart",
    "Mozart's Melodious Abode",
    "Brazil's Bustling Metropolis."
  )
)
```

Generate captions.

```{r}
captions <- paste(
  paste0("<div style='font-size:1.8em;margin-bottom:-0.1em;'><b>", dfr$city, "</b></div><br>"),
  paste0("<div style='text-transform:uppercase;letter-spacing:3px;margin-bottom:0.3em;'><b>", dfr$country, "</b></div><br>"),
  paste0("<div style='line-height:1.2;'>", dfr$tagline, "</div>")
)
```

It would be better to just add CSS classes above and set the styles in a separate CSS document. Refresh the page to see shuffle in action.

```{r}
pixgallery(
  dfr$paths, 
  captions, 
  caption_valign = "center", 
  caption_halign = "center", 
  h = "300px", 
  w = "250px",
  layout = "mosaic",
  border_radius = "10px",
  shuffle = TRUE,
  link = FALSE
)
```
